#!/usr/bin/env bash
# Displays information about subdomains
# another helpful simulator site to help understand awk: https://awk.js.org/

full_domain () {
	for sub in "www" "lb-01" "web-01" "web-02"; do
		dig "$sub"."$1" | awk 'c&&!--c;/ANSWER SECTION/{c=1}' | awk -v subdom="$sub" '{ print "The subdomain " subdom " is a " $4 " record and points to " $5}'
	done
	return 0
}

specific_subdomain () {
	dig "$2"."$1" | awk 'c&&!--c;/ANSWER SECTION/{c=1}' | awk -v subdom="$2" '{ print "The subdomain " subdom " is a " $4 " record and points to " $5}'
	return 0
}

if [ -z "$2" ]; then
	full_domain "$1"
else
	specific_subdomain "$1" "$2"
fi
