#!/usr/bin/env bash
# Configures a nginx server's HTML page
# shellcheck disable=SC2059
sudo sed -i '/http {/a\        add_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf
sudo service nginx restart
