#!/usr/bin/env bash
# Displays a 12 hour 59 minute clock
hour=0
minute=1
while [ $hour -le 12 ]; do
	echo "Hour: $hour"
	while [ $minute -le 59 ]; do
		echo $minute
		let "minute+=1"
	done
	minute=1
	let "hour+=1"
done
